# Generated by Django 4.0.5 on 2022-10-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=200, null=True)),
                ('fileType', models.CharField(max_length=200, null=True)),
                ('fileSize', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
